spring:
  application:
    name: myapp
  main:
    allow-bean-definition-overriding: true
server:
  port: ${PORT:8080}

---
# dev profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/matchsaver
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

---

# prod profile
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    gg.jte: DEBUG
gg:
  jte:
    development-mode: false
    use-precompiled-templates: true