gg:
  jte:
    developmentMode: true

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: matchsaver

  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG