name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SPRING_DATASOURCE_URL: ${{ secrets.JDBC_DATABASE_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.JDBC_DATABASE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.JDBC_DATABASE_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 21

      - name: Build with Maven
        run: mvn clean package --file pom.xml
  deploy:
    name: Deploy to Render
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      deployments: write

    steps:
      - uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: true
          wait_deploy: true
